### ISSUE TITLE
Error on HTTP

### ISSUE THREAD

**Issue by caseywatts** [heroku/heroku-cli-oauth#27]
I was just talking with @mathias and it seems that only `https` URLs are supported as `redirect_uri`'s. We may want to give the user an error/warning if they add a redirect_uri with `http`

**Comment by dickeyxxx** [comment]
we don't allow them https://github.com/heroku/heroku-cli-oauth/blob/master/lib/clients.js#L14

**Comment by dickeyxxx** [comment]
though I don't know why the CLI would be doing the validation here

**Comment by caseywatts** [comment]
For a reproducible example, `heroku clients:create "zzz" http://localhost:5000/auth/heroku/callback` successfully creates a client, even though its protocol is `http`

I'm not sure where that ^ code is triggered - maybe it never catches this sort of scenario?

I'm also surprised API doesn't catch this mistake.

**Comment by mathias** [comment]
@caseywatts It allows localhost to be HTTP it seems: https://github.com/heroku/heroku-cli-oauth/blob/master/lib/clients.js#L7

**Comment by caseywatts** [comment]
aha! that explains the situation :)
