### ISSUE TITLE
--expires_in and --ouput_format do not work as documented

### ISSUE THREAD

**Issue by dnasseri** [heroku/heroku-cli-oauth#31]
Hello there,

I am currently upgrading to the new heroku-cli. I am using Mac OSX

I installed the heroku-cli using the following command:

`brew install heroku`

After running `heroku --version` I see:

```
heroku --version                                                                                                                           12:27:59
heroku-cli/6.8.5-e6953b2 (darwin-x64) node-v7.10.0
```
Running `which heroku` I see the following 
```
which heroku                                                                                                                               12:29:35
/usr/local/bin/heroku
```

So it seems the correct version has been installed. However when running `heroku authorizations:create --expires_in 2` I see the following error: 

```
~ heroku authorizations:create --expires_in 2                                                                                                12:30:02
 ▸    Unexpected argument --expires_in
```

Similarly when I run `heroku authorizations:create --output_format short` I see:
```
heroku authorizations:create --output_format short                                                                                         12:30:58
 ▸    Unexpected argument --output_format
```

However the following does work:

```
heroku authorizations:create --description 'For deploy' --expires-in 12000 --short
```

Is the README out of date or am I missing something? Thanks for the help!

**Comment by dickeyxxx** [comment]
yes, we need to update the reamde. The flags use dashes not underscores
